const STAKE_TOKEN_NAME = 'Stake Token';
const STAKE_TOKEN_SYMBOL = 'STK';
const STAKE_TOKEN_AMOUNT = '100000000000000000000'; // 100e18
const LP_TOKEN_NAME = `Staking LP ${STAKE_TOKEN_NAME}`;
const LP_TOKEN_SYMBOL = `StLP ${STAKE_TOKEN_SYMBOL}`;
const REFERER_BONUS_PERCENT = 0.5;
const INFLUENCER_BONUS_PERCENT = 0.75;
const DEVELOPER_BONUS_PERCENT = 0.2;

module.exports = {
    STAKE_TOKEN_NAME,
    STAKE_TOKEN_SYMBOL,
    STAKE_TOKEN_AMOUNT,
    LP_TOKEN_NAME,
    LP_TOKEN_SYMBOL,
    REFERER_BONUS_PERCENT,
    INFLUENCER_BONUS_PERCENT,
    DEVELOPER_BONUS_PERCENT,
};
